DECLARE @DATA_FIM DATE = '2025-05-15';
DECLARE @DATA_INI DATE = DATEADD(DAY, -20, @DATA_FIM);
WITH EVE_FALTAS AS (
  SELECT CODIGO
  FROM PEVENTO
  WHERE CODIGOCALCULO = 8
    AND VALHORDIAREF = 'D'
),
PRESDIR AS (
  SELECT DISTINCT C.COLIGADA,
    C.CHAPA
  FROM PortalRHDEV..ZCRMPORTAL_HIERARQUIA A
    LEFT JOIN PortalRHDEV..ZCRMPORTAL_HIERARQUIA_GRUPOCARGO B ON B.ID = A.ID_GRUPOCARGO
    LEFT JOIN PortalRHDEV..ZCRMPORTAL_HIERARQUIA_CHAPA C ON C.ID_HIERARQUIA = A.ID
  WHERE (
      B.DESCRICAO = '01 - DIRETOR'
      OR B.DESCRICAO = '00 - PRESIDENTE'
    )
    AND A.INATIVO IS NULL
    AND C.CHAPA IS NOT NULL
),
SUB AS (
  SELECT S.COLIGADA,
    S.CHAPA_GESTOR,
    S.CHAPA_SUBSTITUTO,
    U.NOME,
    U.EMAIL
  FROM PortalRHDEV..ZCRMPORTAL_HIERARQUIA_GESTOR_SUBSTITUTO S
    INNER JOIN PortalRHDEV..ZCRMPORTAL_USUARIO U ON U.ID = S.ID_SUBSTITUTO
  WHERE --S.MODULOS LIKE '%"6"%' AND 
    S.DTFIM >= GETDATE()
    AND S.INATIVO = 0
),
EML AS (
  SELECT DISTINCT A.CHAPA,
    A.NOME,
    A.CODCOLIGADA,
    C.EMAIL EMAIL
  FROM PFUNC A,
    PPESSOA B,
    PortalRHDEV..ZCRMPORTAL_USUARIO C
  WHERE A.CODPESSOA = B.CODIGO
    AND C.LOGIN = B.CPF COLLATE LATIN1_GENERAL_CI_AS
    AND A.CODSITUACAO <> 'D'
),
PAR AS (
  SELECT CODCOLIGADA,
    DIAS_FALTAS,
    DIAS_DE_ESPERA,
    DIAS_PARA_ESCALAR
  FROM PortalRHDEV..ZCRMPORTAL_WORKFLOW_FALTAS_CONFIG
),
LISTA AS (
  SELECT A.CODCOLIGADA,
    A.CHAPA,
    COUNT(CONVERT(DATE, A.DATA)) AS FALTAS,
    MIN(CONVERT(DATE, A.DATA)) AS PRIM_FALTA,
    MAX(CONVERT(DATE, A.DATA)) AS ULT_FALTA
  FROM AMOVFUNDIA A
    LEFT JOIN PAR P ON P.CODCOLIGADA = A.CODCOLIGADA
  WHERE A.CODEVE IN (
      SELECT CODIGO
      FROM EVE_FALTAS
    )
    AND A.DATA >= @DATA_INI
    AND A.DATA <= @DATA_FIM
  GROUP BY A.CODCOLIGADA,
    A.CHAPA,
    P.DIAS_FALTAS
  HAVING COUNT(A.DATA) >= ISNULL(P.DIAS_FALTAS, 10)
),
EVE_OUTROS AS (
  SELECT CODCOLIGADA,
    CHAPA,
    MIN(CONVERT(DATE, DATA)) AS PRIM_NAO_FALTA,
    MAX(CONVERT(DATE, DATA)) AS ULT_NAO_FALTA
  FROM AMOVFUNDIA
  WHERE CODEVE NOT IN (
      SELECT CODIGO
      FROM EVE_FALTAS
    )
    AND DATA >= @DATA_INI
    AND DATA <= @DATA_FIM
  GROUP BY CODCOLIGADA,
    CHAPA
),
LISTA_UNI AS (
  SELECT L.*,
    O.PRIM_NAO_FALTA,
    O.ULT_NAO_FALTA
  FROM LISTA L
    LEFT JOIN EVE_OUTROS O ON O.CODCOLIGADA = L.CODCOLIGADA
    AND O.CHAPA = L.CHAPA
),
TEM_OUTROS_EVE AS (
  SELECT A.CODCOLIGADA,
    A.CHAPA,
    COUNT(CONVERT(DATE, A.DATA)) AS FALTAS
  FROM AMOVFUNDIA A
    INNER JOIN LISTA_UNI L ON L.CODCOLIGADA = A.CODCOLIGADA
    AND L.CHAPA = A.CHAPA
    AND L.ULT_NAO_FALTA IS NOT NULL
  WHERE CODEVE IN (
      SELECT CODIGO
      FROM EVE_FALTAS
    )
    AND DATA >= L.ULT_NAO_FALTA
    AND DATA <= @DATA_FIM
  GROUP BY A.CODCOLIGADA,
    A.CHAPA
),
LISTA_CALC AS (
  SELECT L.*,
    F.CODSITUACAO,
    O.FALTAS FALTAS_AJUSTADAS,
    CASE
      WHEN L.ULT_NAO_FALTA > L.ULT_FALTA THEN 0
      ELSE ISNULL(O.FALTAS, L.FALTAS)
    END FALTAS_FINAIS
  FROM LISTA_UNI L
    LEFT JOIN PFUNC F ON F.CODCOLIGADA = L.CODCOLIGADA
    AND F.CHAPA = L.CHAPA
    LEFT JOIN TEM_OUTROS_EVE O ON O.CODCOLIGADA = L.CODCOLIGADA
    AND O.CHAPA = L.CHAPA
  WHERE F.CODSITUACAO IN ('A')
),
LISTA_G1 AS (
  SELECT L.CODCOLIGADA,
    L.CHAPA,
    L.PRIM_FALTA,
    L.FALTAS_FINAIS,
    G.CHAPA_GESTOR_IMEDIATO,
    CASE
      WHEN P.CHAPA IS NOT NULL THEN 'S'
      ELSE 'N'
    END PRESDIR1
  FROM LISTA_CALC L
    LEFT JOIN PAR R ON R.CODCOLIGADA = L.CODCOLIGADA
    LEFT JOIN CRM_HIERARQUIA3 G ON G.CODCOLIGADA = L.CODCOLIGADA
    AND G.CHAPA = L.CHAPA
    LEFT JOIN PRESDIR P ON P.COLIGADA = L.CODCOLIGADA
    AND P.CHAPA = G.CHAPA_GESTOR_IMEDIATO COLLATE LATIN1_GENERAL_CI_AS
  WHERE L.FALTAS_FINAIS >= ISNULL(R.DIAS_FALTAS, 10)
),
LISTA_G2 AS (
  SELECT L.CODCOLIGADA,
    L.CHAPA,
    L.PRIM_FALTA,
    L.FALTAS_FINAIS,
    L.CHAPA_GESTOR_IMEDIATO AS CHAPA_GESTOR1,
    L.PRESDIR1,
    G.CHAPA_GESTOR_IMEDIATO AS CHAPA_GESTOR2,
    CASE
      WHEN P.CHAPA IS NOT NULL THEN 'S'
      ELSE 'N'
    END PRESDIR2
  FROM LISTA_G1 L
    LEFT JOIN CRM_HIERARQUIA3 G ON G.CODCOLIGADA = L.CODCOLIGADA
    AND G.CHAPA = L.CHAPA_GESTOR_IMEDIATO COLLATE LATIN1_GENERAL_CI_AS
    LEFT JOIN PRESDIR P ON P.COLIGADA = L.CODCOLIGADA
    AND P.CHAPA = G.CHAPA_GESTOR_IMEDIATO COLLATE LATIN1_GENERAL_CI_AS
)
SELECT L.CODCOLIGADA,
  L.CHAPA AS CHAPA_COLAB,
  F0.NOME AS NOME_COLAB,
  U.NOME AS FUNCAO_COLAB,
  L.PRIM_FALTA,
  L.FALTAS_FINAIS,
  L.CHAPA_GESTOR1,
  E1.NOME AS NOME_GESTOR1,
  E1.EMAIL AS EMAIL_GESTOR1,
  L.PRESDIR1,
  S1.CHAPA_SUBSTITUTO AS GESTOR_SUB1,
  S1.NOME AS NOME_SUB1,
  S1.EMAIL AS EMAIL_SUB1,
  L.CHAPA_GESTOR2,
  E2.NOME AS NOME_GESTOR2,
  E2.EMAIL AS EMAIL_GESTOR2,
  L.PRESDIR2,
  S2.CHAPA_SUBSTITUTO AS GESTOR_SUB2,
  S2.NOME AS NOME_SUB2,
  S2.EMAIL AS EMAIL_SUB2
FROM LISTA_G2 L
  LEFT JOIN SUB S1 ON S1.COLIGADA = L.CODCOLIGADA
  AND S1.CHAPA_GESTOR = L.CHAPA_GESTOR1 COLLATE LATIN1_GENERAL_CI_AS
  LEFT JOIN SUB S2 ON S2.COLIGADA = L.CODCOLIGADA
  AND S2.CHAPA_GESTOR = L.CHAPA_GESTOR2 COLLATE LATIN1_GENERAL_CI_AS
  LEFT JOIN EML E1 ON E1.CODCOLIGADA = L.CODCOLIGADA
  AND E1.CHAPA = L.CHAPA_GESTOR1 COLLATE LATIN1_GENERAL_CI_AS
  LEFT JOIN EML E2 ON E2.CODCOLIGADA = L.CODCOLIGADA
  AND E2.CHAPA = L.CHAPA_GESTOR2 COLLATE LATIN1_GENERAL_CI_AS
  LEFT JOIN PFUNC F0 ON F0.CODCOLIGADA = L.CODCOLIGADA
  AND F0.CHAPA = L.CHAPA COLLATE LATIN1_GENERAL_CI_AS
  LEFT JOIN PFUNCAO U ON U.CODCOLIGADA = F0.CODCOLIGADA
  AND U.CODIGO = F0.CODFUNCAO